### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by allanburleson** [V1Soft/textbasedgame#16]
The code is getting very confusing as it grows. Will someone add more comments and organize things?

**Comment by DaVinci789** [comment]
Look at http://legacy.python.org/dev/peps/pep-0008/ or PEP 8 for style guidelines
PEP 20 is also a good resource https://www.python.org/dev/peps/pep-0020/
I'll also try to add comments and documentation as time goes on

**Comment by allanburleson** [comment]
I use an IDE that automatically tells me if I'm not following those guidelines (PyCharm). I'll get around to fixing that stuff eventually.

**Comment by ghost** [comment]
I have reorganized the code and begun documentation

**Comment by allanburleson** [comment]
Much better now.
