### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by ghost** [V1Soft/textbasedgame#17]
Languages are a problem. While I am creating fixes for them, they're still a mighty mess. Enable a language from launch rather on the creation of a new account. Also, limit the usage of languages in the code until further notice.

**Comment by ghost** [comment]
This problem is still larger than I thought, disabling the feature altogether for now.

**Comment by allanburleson** [comment]
Abandoning them is probably best until the game is better

**Comment by ghost** [comment]
Agreed.
