### ISSUE TITLE
Key Error raised from 'firstTime'

### ISSUE THREAD

**Issue by DaVinci789** [V1Soft/textbasedgame#2]
Whenever I try to start this, a keyerror is raised from shelve.py

Traceback (most recent call last):
  File "/usr/lib/python3.5/shelve.py", line 111, in **getitem**
    value = self.cache[key]
KeyError: 'firstTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "programming/git_clone/textbasedgame/main.py", line 207, in <module>
    if not saveFile['firstTime']:
  File "/usr/lib/python3.5/shelve.py", line 113, in **getitem**
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'firstTime'

cloned from commit 5a593f19ec0ec6ed7c81917722c263edaca15e05

**Comment by allanburleson** [comment]
I know this is kind of annoying, but you have to open a Python shell in the textbasedgame directory and type this (I'm working on a solution):

import shelve
shelf = shelve.open('savefile')
shelf['firstTime'] = True
shelf.close()

Then you should be able to run the game with savefile functionality.

**Comment by ghost** [comment]
I have created a Temporary Patch for this Issue. All seems to be functional.
If this works for Allan, this issue may be closed.

**Comment by allanburleson** [comment]
Let me try it

**Comment by ghost** [comment]
Also ported it to python3.

**Comment by allanburleson** [comment]
See latest commit. Fixed.
