### ISSUE TITLE
Arrow Keys.

### ISSUE THREAD

**Issue by ghost** [V1Soft/textbasedgame#21]
This is frustrating. I've been working with curses, but _curses_ curses is _blech_ blech

**Comment by allanburleson** [comment]
What do we need arrow keys for?

**Comment by ghost** [comment]
when typing, when you make a mistake, you have to backspace all of the way, instead of the arrow keys just moving the textblock cursor

**Comment by allanburleson** [comment]
Right. Hmm.

**Comment by ghost** [comment]
Ideas?

**Comment by allanburleson** [comment]
Use curses?

**Comment by ghost** [comment]
_curses_ I was afraid of that.

Thank you,
   Connor Haight, Central Magnet Student

**Comment by ghost** [comment]
I will never reply with my email again, stupid sig

**Comment by ghost** [comment]
Found a fix... import readline
