### ISSUE TITLE
Quit Issue

### ISSUE THREAD

**Issue by ghost** [V1Soft/textbasedgame#3]
When quitting, and replying yes to "are you sure you want to quit...", it cancels quitting and wipes progress rather than saving it.

"Welcome to textbasedgame!
This game is released under the GPL.
Copyright V1Soft 2015
Type "help" for help.
: quit
Are you sure you want to quit? Your progress will be saved.
yes
Cancelled.
New game set up. Welcome!"

**Comment by allanburleson** [comment]
Working on it

**Comment by allanburleson** [comment]
Okay. Just added ability to type both 'y' and 'yes' for affirmative.
I can't reproduce the wiping bug you experienced.
