### ISSUE TITLE
Object List Bug

### ISSUE THREAD

**Issue by ghost** [V1Soft/textbasedgame#8]
+----------------------------------------------+
| Welcome to textbasedgame!                    |
| This game is released under the GPL.         |
| Copyright V1Soft 2015                        |
+----------------------------------------------+

Do you want to:
1. Start a new game (new)
2. Continue from a previous save (continue) or
3. Exit the game (quit)
: new
Are you sure you want to reset all data?
: y
New game set up. Welcome!
Type "help" for help.
: help
Possible commands:
help--show this message
interact--find another person to interact with
money--show amount of money
inventory--list inventory items
health--show health
quit--quit game
reset--reset progress
: inventory
<obj.Weapon object at 0x7fbf0a69cc18>

**Comment by allanburleson** [comment]
Try again now. This is probably fixed.
