### ISSUE TITLE
Possible Assassin-Old Lady Cross Bug

### ISSUE THREAD

**Issue by ghost** [V1Soft/textbasedgame#9]
You see a(n) assassin in the distance. Do you choose to approach (y/n)?
y
The assassin pulls out a(n) cane threateningly.
The assassin has been defeated!
Your power level is now 10.25
cane added to inventory.
Opponent dropped 53 coins

**Comment by allanburleson** [comment]
That's not a bug. Old Ladies aren't cane wielding yet.
